
import React, { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { X, CheckCircle } from 'lucide-react';

interface QuickHelpModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const QuickHelpModal: React.FC<QuickHelpModalProps> = ({
  isOpen,
  onClose
}) => {
  const [dontShowAgain, setDontShowAgain] = useState(false);

  const handleClose = () => {
    if (dontShowAgain) {
      localStorage.setItem('celestialNexusHelpDismissed', 'true');
    }
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div 
      className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50"
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '12px',
        boxSizing: 'border-box'
      }}
    >
      <Card 
        className="bg-gradient-to-br from-purple-900/95 to-cyan-900/95 border-2 border-purple-400/50 relative backdrop-blur-xl shadow-2xl rounded-2xl overflow-hidden flex flex-col"
        style={{
          width: '300px',
          maxWidth: '300px',
          height: '350px',
          maxHeight: '350px',
          boxSizing: 'border-box',
          borderRadius: '12px'
        }}
      >
        {/* Enhanced glassmorphism inner glow */}
        <div className="absolute inset-0 bg-gradient-to-br from-white/15 via-transparent to-black/10 pointer-events-none rounded-2xl" />
        
        <div className="flex justify-between items-center p-3 border-b border-white/20 flex-shrink-0">
          <h2 className="text-sm font-bold text-white flex items-center gap-2">
            <span>🎯</span>
            Quick Guide
          </h2>
          <Button
            onClick={handleClose}
            variant="ghost"
            size="sm"
            className="text-white hover:bg-white/15 p-1 h-6 w-6 rounded-full transition-all duration-200 flex-shrink-0"
          >
            <X size={12} />
          </Button>
        </div>
        
        <div 
          className="p-3 space-y-2 flex-1 overflow-y-auto scrollbar-hide"
          style={{
            maxHeight: '240px',
            overflowY: 'auto',
            overflowX: 'hidden'
          }}
        >
          <div className="text-xs text-white/90 space-y-2">
            <p><strong className="text-purple-300 font-semibold">💠 Mana:</strong> Generated by Fantasy structures like Altars and Towers</p>
            <p><strong className="text-cyan-300 font-semibold">⚡ Energy:</strong> Produced by Sci-Fi tech like Reactors and Stations</p>
            <p><strong className="text-yellow-300 font-semibold">🌌 Convergence:</strong> Combine both realms when you reach 1000 total resources</p>
            <p><strong className="text-orange-300 font-semibold">🔮 Shards:</strong> Unlock powerful Hybrid upgrades that boost both realms</p>
          </div>
          
          <div className="pt-2 border-t border-white/20">
            <p className="text-xs text-white/80 mb-3 font-medium">
              <strong>Tip:</strong> Tap structures to upgrade them, switch realms to build different tech, and use the Tap button for quick resources!
            </p>
            
            <div className="flex items-center gap-2 mb-3">
              <Button
                onClick={() => setDontShowAgain(!dontShowAgain)}
                variant="ghost"
                size="sm"
                className="p-0 h-auto text-white/70 hover:text-white transition-colors duration-200"
              >
                <CheckCircle 
                  size={12} 
                  className={dontShowAgain ? 'text-green-400' : 'text-white/40'} 
                />
                <span className="ml-1 text-xs">Don't show this again</span>
              </Button>
            </div>
            
            <Button
              onClick={handleClose}
              className="w-full bg-gradient-to-r from-purple-600 to-cyan-600 hover:from-purple-500 hover:to-cyan-500 font-semibold transition-all duration-300 h-8 text-sm"
            >
              Got it!
            </Button>
          </div>
        </div>
      </Card>
    </div>
  );
};
